language: android

android:
  components:
    - tools
    - platform-tools
    - platform-tools-25
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
jdk:
    - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
before_install:
  - chmod +x gradlew

script:
   - ./gradlew clean assemble test check connectedAndroidTest --info --stacktrace
