version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-30-alpha
    steps:
      - run:
          name: Build debug APK
          command: |
            ./gradlew :app:assembleDebug
